baseURL = 'https://blog.0xnullpath.cc/'
languageCode = 'zh-cn'
title = 'Code Now'
theme = 'paper'

# Permalink settings
[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

# Main navigation
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 4

[params]
  author = 'LuYanFCP'
  color = 'linen'
  math = true
  disableHLJS = true
  mainSections = ['posts']
  description = '“Wir müssen wissen, wir werden wissen.”— David Hilbert'
  avatar = 'https://github.com/luyanfcp.png'
  name = '0xNullPath'
  bio = '“Wir müssen wissen, wir werden wissen.”— David Hilbert'
  twitter = 'luyanfcp'
  github = 'luyanfcp'
  rss = true

  # Custom footer supports Markdown and {Year}.
  footer = "&copy; [0xNullPath](https://blog.0xnullpath.work) 2023-{Year} | [GitHub](https://github.com/LuYanFCP) | [Twitter](https://x.com/luyanfcp)"
  
  [params.githubSync]
    enabled = true
    username = "luyanfcp"
    branch = "master"
    token = ""  # Optional, prefer passing this via CLI.

    # README sync
    readme_to_index = true
    readme_path = "content/about.md"
    readme_title = "关于我"

    # Release issue sync
    releases_dir = "content/posts"

    exclude_tags = ["Release"]  # Tags to exclude.

    # Multi-repo issue sync
    [[params.githubSync.issue_repos]]
      owner = "luyanfcp"
      repo = "note-snippet"
  
[markup]  
  [markup.goldmark]  
    [markup.goldmark.renderer]  
      unsafe = true  
    [markup.goldmark.extensions]
      footnote = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
      [markup.goldmark.extensions.alerts]
        enable = true
  
  [markup.tableOfContents]  
    endLevel = 3  
    ordered = false  
    startLevel = 2  
  
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    tabWidth = 4

  
  [markup.render]  
    [markup.render.mermaid]  
      enable = true

