/**
 * 网站配置
 */
export const siteConfig = {
  // 网站名称配置
  name: "0xNullPath Blog",
  titlePrefix: "0xNullPath",
  titleSuffix: "Blog",
  
  // 网站元数据
  description: "no mountain too high，no ocean too deep.",
  author: "0xNullPath",
  
  // 社交链接
  github: "https://github.com/LuYanFCP",
  twitter: "",
  
  // 底部版权信息
  copyright: `© ${new Date().getFullYear()} generated by Claude 3.7 Sonnet.`,
  
  icp: "",
};
